services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    Letkode\HttpExceptionBundle\Locale\RequestLocaleResolver: ~

    Letkode\HttpExceptionBundle\Contract\LocaleResolverInterface:
        alias: Letkode\HttpExceptionBundle\Locale\RequestLocaleResolver

    Letkode\HttpExceptionBundle\EventListener\ExceptionListener:
        arguments:
            $debug: '%kernel.debug%'
            $pathPrefix: '%letkode.http_exception.path_prefix%'
        tags:
            - name: kernel.event_listener
              event: kernel.exception
              method: __invoke
              priority: '%letkode.http_exception.listener_priority%'
